### ISSUE TITLE
Prvobitni dizajn

### ISSUE THREAD

**Issue by harunridjevic** [harunridjevic/korpagen#2]

**Comment by sEhA1234** [comment]
/* Style for the body */
body {
  font-family: Arial, sans-serif;
  background-color: #f5f5f5;
}

/* Style for the articles container */
.articles-container {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  align-items: center;
  margin: 20px auto;
  max-width: 1200px;
}

/* Style for the article card */
.article-card {
  background-color: #fff;
  box-shadow: 0 2px 4px rgba(0,0,0,0.1);
  padding: 20px;
  margin: 10px;
  max-width: 300px;
  text-align: center;
}

/* Style for the article title */
.article-title {
  font-size: 24px;
  font-weight: bold;
  margin-bottom: 10px;
}

/* Style for the article content */
.article-content {
  font-size: 16px;
  line-height: 1.5;
  margin-bottom: 10px;
}

/* Style for the generate button */
#generate-button {
  background-color: #007bff;
  border: none;
  color: #fff;
  padding: 10px 20px;
  font-size: 16px;
  font-weight: bold;
  border-radius: 5px;
  cursor: pointer;
  margin: 20px auto;
  display: block;
}
